StockControl/urls.py
from django.contrib import admin
from django.urls import path
from compra import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('signup/', views.signup, name='signup'),
    path('login/', views.iniciar_sesion, name='login'),    
    path('logout/', views.cerrar_sesion, name='logout'),    
    path('', views.Home , name='home'),
    path('producto/agregar/', views.agregar_producto, name='agregar_producto'),
    path('proveedor/agregar/', views.agregar_proveedor, name='agregar_proveedor'),
    path('productos/', views.listar_productos, name='listar_productos'),
    path('proveedores/', views.listar_proveedores, name='listar_proveedores'),
    path('todos/', views.listar_todos, name='listar_todos'),
    path('productos/<int:producto_id>/', views.detalle_producto, name='detalle_producto'),
    path('proveedor/<int:proveedor_id>/', views.detalle_proveedor, name='detalle_proveedor'),
    path('productos/<int:producto_id>/eliminar', views.eliminar_producto, name='eliminar_producto'),
    path('proveedor/<int:proveedor_id>/eliminar', views.eliminar_proveedor, name='eliminar_proveedor'),
]

compra/urls.py
from django.urls import path
from . import views
urlpatterns = [
]

compra/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Proveedor(models.Model):
    nombre = models.CharField(max_length=50)
    apellido = models.CharField(max_length=50)
    dni = models.IntegerField()
    
    
    class Meta:
        verbose_name = 'Proveedor'
        verbose_name_plural = 'Proveedores'
    
    def __str__(self):
        return f"{self.apellido}, {self.nombre}."


class Producto(models.Model):
    nombre = models.CharField(max_length=50)
    precio = models.FloatField()
    stock_actual = models.PositiveIntegerField()
    proveedor = models.ForeignKey(Proveedor, on_delete=models.CASCADE)
    
    
    class Meta:
        verbose_name = 'Producto'
        verbose_name_plural = 'Productos'
        
    def __str__(self):
        return f'{self.nombre} ({self.stock_actual})'

compra/forms.py
from django.forms import ModelForm
from .models import Producto, Proveedor

class AgregarProductoForm(ModelForm):
    class Meta:
        model = Producto
        fields = ['nombre','precio', 'stock_actual', 'proveedor']





class AgregarProveedorForm(ModelForm):
    class Meta:
        model = Proveedor
        fields = ['nombre', 'apellido', 'dni']
    
    

StockControl/views.py
from django.shortcuts import render

def Home(request):
    return render(request, 'home.html')

compra/views.py
from django.http import HttpResponse
from django.shortcuts import redirect, render, get_object_or_404
from .forms import AgregarProductoForm, AgregarProveedorForm
from .models import Producto, Proveedor
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.decorators import login_required




def signup(request):
    if request.method == 'GET':
        return render(request, 'signup.html', {'form': UserCreationForm})
    else:
            if request.POST['password1'] == request.POST['password2']:
                try:
                    usuario = User.objects.create_user(username=request.POST['username'], password=request.POST['password1'])
                    usuario.save()
                    login(request, usuario)
                    return redirect('home')
                except:
                    return render(request, 'signup.html', {'form': UserCreationForm, 'error':'ERROR: El usuario ya existe'})
            return render(request, 'signup.html', {'form': UserCreationForm, 'error':'ERROR: Las contraseñas no coinciden'})

def iniciar_sesion(request):
    if request.method == 'GET':
        return render(request, 'login.html', {'form': AuthenticationForm})
    else:
        usuario = authenticate(request, username=request.POST['username'], password=request.POST['password'])
        if usuario is None:
            return render(request, 'login.html', {'form': AuthenticationForm, 'error':'Error: El usuario o contraseña es incorrecto'})
        else:
            login(request, usuario)
            return redirect('home')
    
    return render(request, 'login.html')


def cerrar_sesion(request):
    logout(request)
    return redirect('login')



def Home(request):
    return render(request, 'home.html')





@login_required
def listar_proveedores(request):
    proveedores = Proveedor.objects.all()
    return render(request, 'mostrar_proveedores.html', {'proveedores' : proveedores})

@login_required
def listar_productos(request):
    productos = Producto.objects.all()
    return render(request, 'mostrar_productos.html', {'productos': productos})

@login_required
def listar_todos(request):
    proveedores = Proveedor.objects.all()
    productos = Producto.objects.all()
    return render(request, 'mostrar_todo.html', {'proveedores' :proveedores, 'productos':productos})




@login_required
def detalle_proveedor(request, proveedor_id):
    if request.method == 'GET':
        proveedor = get_object_or_404(Proveedor, pk=proveedor_id)
        form = AgregarProveedorForm(instance=proveedor)
        return render(request, 'detalle_proveedor.html', {'proveedor': proveedor, 'form': form})
    else:
        try:
            proveedor = get_object_or_404(Proveedor, pk = proveedor_id)
            formulario = AgregarProveedorForm(request.POST, instance=proveedor)
            formulario.save()
            return redirect('listar_proveedores')
        except ValueError:
            return render(request, 'detalle_proveedor.html', {'proveedor': proveedor , 'form': form, 'error': 'Error en los datos para actualizar.'})

@login_required
def detalle_producto(request, producto_id):
    if request.method == 'GET':
        proveedores = Proveedor.objects.all()
        producto = get_object_or_404(Producto, pk=producto_id)
        form = AgregarProductoForm(instance=producto)
        return render(request, 'detalle_producto.html', {'producto': producto, 'form': form, 'proveedores': proveedores })
    else:
        try:
            producto = get_object_or_404(Producto, pk = producto_id)
            formulario = AgregarProductoForm(request.POST, instance=producto)
            formulario.save()
            return redirect('listar_productos')
        except ValueError:
            return render(request, 'detalle_producto.html', {'producto': producto , 'form': form, 'error': 'Error en los datos para actualizar.'})



@login_required
def eliminar_producto(request, producto_id):
    producto = get_object_or_404(Producto, pk=producto_id)
    producto.delete()
    return redirect('listar_productos')


@login_required
def eliminar_proveedor(request, proveedor_id):
    proveedor = get_object_or_404(Proveedor, pk=proveedor_id)
    proveedor.delete()
    return redirect('listar_proveedores')




@login_required
def agregar_producto(request):
    
    if request.method == 'GET':
        proveedores = Proveedor.objects.all()
        return render(request, 'agregar_producto.html', {'form': AgregarProductoForm, 'proveedores': proveedores})
    else:
        try:
            form = AgregarProductoForm(request.POST)
            nuevo_producto = form.save(commit=False)
            nuevo_producto.save()
            return redirect('listar_productos')
        except ValueError:
            return render(request, 'agregar_producto.html', {
                'form': AgregarProductoForm,
                'error': 'Por favor, ingrese datos válidos'
                })


@login_required
def agregar_proveedor(request):
    
    if request.method == 'GET':
        return render(request, 'agregar_proveedor.html', {'form': AgregarProveedorForm})
    else:
        try:
            form = AgregarProveedorForm(request.POST)
            nuevo_proveedor = form.save(commit=False)
            nuevo_proveedor.save()
            return redirect('listar_proveedores')
        except ValueError:
            return render(request, 'agregar_proveedor.html', {
                'form': AgregarProductoForm,
                'error': 'Por favor, ingrese datos válidos'
                })

templates/agregar_producto.html
{% extends 'base.html' %}
{% load static %}

{% block contenido %}
<main class="container">
    <div class="row">
        <div class="col-12">
            <h1 class="titulo">AGREGAR PRODUCTO</h1>
        </div>
        <div class="col-12">
          <p class="eslogan">
            Por favor complete los campos para agregar el producto.
          </p>
        </div>
    <div class="row">
        <div class="col-12">
        </div>
        <div class="col-md-4 offset-md-4">            
            <form action="/producto/agregar/" method="POST" class="card mt-5 mb-5">
                {% csrf_token %}
                {{error}}
                <div class="card-body">
                  <div class="form-group mt-3">
                    <label for="id_nombre">Nombre:</label>
                    <input class="form-control"type="text"  name="nombre" maxlength="50" required id="id_nombre">
                  </div>
                  <div class="form-group mt-3">
                    <label for="id_precio">Precio:</label>
                    <input class="form-control" type="number" min="0" step="0.01" name="precio" maxlength="50" required="" id="id_precio">
                  </div>
                  <div class="form-group mt-3">
                    <label for="id_stock">Stock:</label>
                    <input class="form-control" type="number"  min="0" name="stock_actual" required="" id="id_stock">
                  </div>
                  <div class="form-group mt-3">
                    <label for="id_proveedor">Proveedor:</label>
                    <select class="form-control" name="proveedor" required="" id="id_proveedor">
                        <option value="" selected="">Seleccionar una opción.</option>
                        {% for p in proveedores  %}
                        <option value="{{p.id}}">{{p.apellido}}, {{p.nombre}}.</option>
                        {% endfor %}
                    </select>
                  </div>
                  <div class="">
                        <button class="btn btn-success mt-3" style="width: 100%;">Agregar producto</button>
                  </div>
                </div>
              </form>
        </div>
    </div>
</main>

{% endblock contenido %}

templates/agregar_proveedor.html
{% extends 'base.html' %}
{% load static %}

{% block contenido %}
<main class="container">
    <div class="row">
        <div class="col-12">
            <h1 class="titulo">AGREGAR PROVEEDOR</h1>
        </div>
        <div class="col-12">
          <p class="eslogan">
            Por favor complete los campos para agregar el proveedor.
          </p>
        </div>
    <div class="row">
        <div class="col-12">
        </div>
        <div class="col-md-4 offset-md-4">            
            <form action="/proveedor/agregar/" method="POST" class="card mt-5 mb-5">
                {% csrf_token %}
                {{error}}
                <div class="card-body">
                  <div class="form-group mt-3">
                    <label for="id_nombre">Nombre:</label>
                    <input class="form-control"type="text" name="nombre" maxlength="50" required id="id_nombre">
                  </div>
  
                  <div class="form-group mt-3">
                    <label for="id_apellido">Apellido:</label>
                    <input class="form-control" type="text" name="apellido" maxlength="50" required="" id="id_apellido">
                  </div>
                  <div class="form-group mt-3">
                    <label for="id_dni">DNI:</label>
                    <input class="form-control" type="number" name="dni" required="" id="id_dni">
                  </div>
                  <!-- <div class="form-group mt-3">
                    <label for="id_password">Contraseña:</label>
                    <input class="form-control" type="text" name="apellido" maxlength="50" required="" id="id_apellido">
                  </div> -->
                  <div class="">
                        <button class="btn btn-success mt-3" style="width: 100%;">Agregar Proveedor</button>
                  </div>
                </div>
              </form>
        </div>
    </div>
</main>

{% endblock contenido %}

templates/base.html
{% load static %}
<!doctype html>
<html lang="es">
    <head>
        <title>Title</title>
        <!-- Required meta tags -->
        <meta charset="utf-8" />
        <meta
            name="viewport"
            content="width=device-width, initial-scale=1, shrink-to-fit=no"
        />
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Nunito:ital,wght@0,200..1000;1,200..1000&display=swap" rel="stylesheet">
        <!-- Bootstrap CSS v5.2.1 -->
        <link
            href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
            rel="stylesheet"
            integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN"
            crossorigin="anonymous"
        />
        <link rel="stylesheet" href="{% static '/css/style.css' %}">
    </head>
    <body class="fondo">
        <header>
            <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
                <div class="container">
                    <a class="navbar-brand" href="{% url 'home' %}">StockControl</a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                        <div class="navbar-nav">
                            {% if user.is_authenticated %}
                            <a class="nav-link" href="{% url 'home' %}">Inicio</a>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown">Productos</a>
                                <ul class="dropdown-menu bg-dark">
                                    <li><a class="dropdown-item" style="color: #777 !important;" href="{% url 'listar_productos' %}">Mostrar</a></li>
                                    <li><a class="dropdown-item" style="color: #777 !important;" href="{% url 'agregar_producto' %}">Añadir</a></li>
                                </ul>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown">Proveedores</a>
                                <ul class="dropdown-menu bg-dark" >
                                    <li><a class="dropdown-item" style="color: #777 !important;" href="{% url 'listar_proveedores' %}">Mostrar</a></li>
                                    <li><a class="dropdown-item" style="color: #777 !important;" href="{% url 'agregar_proveedor' %}">Añadir</a></li>
                                </ul>
                            </li>
                            <a class="nav-link" href="{% url 'listar_todos' %}">Mostrar todos.</a>
                            <a class="nav-link active" href="{% url 'logout' %}">Cerrar sesión</a>
                            
                            {% else %}
                            <a class="nav-link active" href="{% url 'login' %}" >Iniciar sesión</a>
                            <a class="nav-link active" href="{% url 'signup' %}">Crear Cuenta</a>
                            {% endif %}
                            
                        </div>
                    </div>
                </div>
            </nav>
        </header>
        <main>
            
            {% block contenido %}            {% endblock contenido %}
        </main>
        <footer class="bg-body-tertiary text-center text-lg-start">
            <div class="text-center p-3" style="background-color: #212529; color: #fff;">
                © 2024 Copyright:
                <a class="text-body" style="color: #fff !important;" target="_blank" href="https://instagram.com/pegoraro.manuell">Pegoraro Manuel</a>
            </div>
        </footer>
        <script
            src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
            integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
            crossorigin="anonymous"
        ></script>
        <script
            src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js"
            integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+"
            crossorigin="anonymous"
        ></script>
    </body>
</html>

templates/detalle_producto.html
{% extends 'base.html' %}
{% load static %}

{% block contenido %}
<main class="container">
    <div class="row">
        <div class="col-12">
            <h1 class="titulo">ACTUALIZAR PRODUCTO</h1>
        </div>
    <div class="row">
        <div class="col-12">
        </div>
        <div class="col-md-4 offset-md-4">            
            <form method="POST" class="card mt-5 mb-5">
                {% csrf_token %}
                {{error}}
                <div class="card-body">
                    <div class="form-group mt-3">
                        <label for="id_nombre">Nombre:</label>
                        <input class="form-control"type="text" name="nombre" value="{{producto.nombre}}" maxlength="50" required id="id_nombre">
                    </div>
                    <div class="form-group mt-3">
                        <label for="id_precio">Precio:</label>
                        <input class="form-control"  value="{{producto.precio}}"type="number" step="0.01" min="0" name="precio" maxlength="50" required="" id="id_precio">
                    </div>
                    <div class="form-group mt-3">
                        <label for="id_stock">Stock:</label>
                        <input class="form-control" type="number"
                    value="{{producto.stock_actual}}" min="0" name="stock_actual" required="" id="id_stock">
                </div>
                <div class="form-group mt-3">
                    <label for="id_proveedor">Proveedor:</label>
                    <select class="form-control" name="proveedor" required="" id="id_proveedor">
                        <option value="" selected="">Seleccionar una opción.</option>
                        {% for p in proveedores  %}
                            {% if producto.proveedor.id == p.id %}
                            <option selected value="{{p.id}}">{{p.apellido}}, {{p.nombre}}.</option>
                            {% else %}
                            <option value="{{p.id}}">{{p.apellido}}, {{p.nombre}}.</option>
                            {% endif %}

                        {% endfor %}
                    </select>
                </div>
                <div class="">
                    <button class="btn btn-warning mt-3" style="width: 100%;">Actualizar producto</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</main>

{% endblock contenido %}

templates/detalle_proveedor.html
{% extends 'base.html' %}
{% load static %}

{% block contenido %}
<main class="container">
    <div class="row">
        <div class="col-12">
            <h1 class="titulo">ACTUALIZAR PROVEEDOR</h1>
        </div>
    <div class="row">
        <div class="col-12">
        </div>
        <div class="col-md-4 offset-md-4">            
            <form method="POST" class="card mt-5 mb-5">
                {% csrf_token %}
                {{error}}
                <div class="card-body">
                <div class="form-group mt-3">
                    <label for="id_nombre">Nombre:</label>
                    <input class="form-control"type="text" name="nombre" value="{{proveedor.nombre}}" maxlength="50" required id="id_nombre">
                </div>
                <div class="form-group mt-3">
                    <label for="id_apellido">Apellido:</label>
                    <input class="form-control"  value="{{proveedor.apellido}}"type="text" name="apellido" maxlength="50" required="" id="id_apellido">
                </div>
                <div class="form-group mt-3">
                    <label for="id_dni">DNI:</label>
                    <input class="form-control" type="number"
                    value="{{proveedor.dni}}" min="0" name="dni" required="" id="id_proveedor">
                </div>
                <div class="">
                    <button class="btn btn-warning mt-3" style="width: 100%;">Actualizar proveedor</button>
                </div>
                </div>
            </form>
        </div>
    </div>
</main>

{% endblock contenido %}

templates/home.html
{% extends 'base.html' %}
{% load static %}


{% block contenido %}

<div class="container-fluid fondo pt-3">
    <div class="row">
        <div class="col-12">
            <h1 class="titulo">StockControl</h1>
        </div>
        <div class="col-12">
            <p class="eslogan">Control total, sin complicaciones</p>
        </div>
    </div>
    <div class="container-fluid">
        <div class="row">
            
            <div class="col">
                <!-- Carousel -->
                <div id="demo" class="carousel slide" data-bs-ride="carousel">

                    <!-- Indicators/dots -->
                    <div class="carousel-indicators">
                        <button type="button" data-bs-target="#demo" data-bs-slide-to="0" class="active"></button>
                        <button type="button" data-bs-target="#demo" data-bs-slide-to="1"></button>
                        <button type="button" data-bs-target="#demo" data-bs-slide-to="2"></button>
                    </div>
            
                <!-- The slideshow/carousel -->

                <div class="carousel-inner">
                    <div class="carousel-item active">
                        <img src="{% static '/img/img-1.jpg' %}" alt="imagen de muestra 1" height="400px" class="object-fit-cover d-block w-100">
                    </div>
                    <div class="carousel-item">
                        <img src="{% static '/img/img-2.jpg' %}" alt="imagen de muestra 2" height="400px" class="object-fit-cover d-block w-100">
                    </div>
                    <div class="carousel-item">
                        <img src="{% static '/img/img-3.jpg' %}" alt="Imagen de muestra 3" height="400px"  class="object-fit-cover d-block w-100">
                    </div>
                </div>
                
                <!-- Left and right controls/icons -->
                <button class="carousel-control-prev" type="button" data-bs-target="#demo" data-bs-slide="prev">
                    <span class="carousel-control-prev-icon"></span>
                </button>
                <button class="carousel-control-next" type="button" data-bs-target="#demo" data-bs-slide="next">
                    <span class="carousel-control-next-icon"></span>
                </button>
                </div>
            
            </div>
        </div>
    </div>

    
    <div class="row mt-5 pt-5">
        <div class="col-12">
            <h2 class="display-4 text-center">Sobre la página</h2>
            <div class="col mb-5">
                <p class="sobre-pagina_texto">StockControl es una página en la que se podrá de cargar, editar y eliminar, tanto productos como proveedores.</p>
            </div>

            
            {% if user.is_authenticated %}
            
            {% else %}
                <div class="col-12">
                    <h3 class="display-5 text-center mt-5">Inicia sesión o crea tu cuenta</h3>
                    <div class="text-center m-5">
                        <a class="btn btn-dark mr-3" href="/login/">Inicia sesión</a>
                        <a class="btn btn-dark ml-3" href="/signup/">Crear cuenta</a>
                    </div>
                </div>

            {% endif %}
                
        </div>
    </div>
    
</div>

{% endblock contenido %}

templates/login.html
{% extends 'base.html' %}
{% load static %}


{% block contenido %}

<main class="container">
    <div class="row">
        <div class="col-12">
        </div>
        <div class="col-md-4 offset-md-4">            
            <form action="{% url 'login' %}" method="POST" class="card mt-5 mb-5">
                {% csrf_token %}
                {{error}}
                <h1 class="titulo">Iniciar Sesión</h1>
                <div class="card-body">
                  <div class="form-group mt-3">
                    <label for="username">Nombre de usuario:</label>
                    <input class="form-control" name="username" autocomplete="username" id="username" type="text" placeholder="Ingrese su usuario" required>
                  </div>
  
                  <div class="form-group mt-3">
                    <label for="id_password">Contraseña:</label>
                    <input class="form-control" name="password" id="id_password" type="password" placeholder="Ingrese su contraseña" required>
                  </div>
                  <div class="">
                        <button class="btn btn-dark mt-3" style="width: 100%;">Iniciar Sesión</button>
                  </div>
                </div>
              </form>
        </div>
    </div>

</main>



{% endblock contenido %}
    

templates/mostrar_productos.html
{% extends 'base.html' %}
{% load static %}



{% block contenido %}
<main class="container">
    <div class="row rellenar">
        <div class="col-12">
            <div class="titulo">
                Productos
            </div>
        </div>
        <div class="col-12">
            <p class="eslogan">
                En la siguiente tabla podrá visualizar, editar y eliminar los productos que se han guardado en la base de datos.
            </p>
        </div>
        <div class="col-8 offset-2 mt-5">
            <div class="col-2 offset-10 mb-2">
                <a href="{% url 'agregar_producto' %}" class="btn btn-success btn-agregar">
                    <img width="26" height="26" src="https://img.icons8.com/sf-black/64/add.png" alt="add"/>
                    Agregar
                </a>
            </div>
            <table class="table table-dark tabla-estilo text-center">
                <thead>
                    <tr>
                        <th scope="col">Nombre</th>
                        <th scope="col">Precio</th>
                        <th scope="col">Stock</th>
                        <th scope="col">Proveedor</th>
                        <th scope="col">Acciones</th>
                    </tr>
                </thead>
                <tbody>
{% for p in productos %}
                    <tr>
                    <th class="table-info" scope="row">{{p.nombre}}</th>
                    <td class="table-info">${{p.precio}}</td>
                    <td class="table-info">{{p.stock_actual}}</td>
                    <td class="table-info">{{p.proveedor.apellido}}, {{p.proveedor.nombre}} </td>
                    <td class="table-info">
                        <a class="btn btn-warning" href="{% url 'detalle_producto' p.id %}" role="button"><svg xmlns="http://www.w3.org/2000/svg" x="0px" y="0px" width="20" height="20" viewBox="0 0 30 30">
                            <path d="M 22.828125 3 C 22.316375 3 21.804562 3.1954375 21.414062 3.5859375 L 19 6 L 24 11 L 26.414062 8.5859375 C 27.195062 7.8049375 27.195062 6.5388125 26.414062 5.7578125 L 24.242188 3.5859375 C 23.851688 3.1954375 23.339875 3 22.828125 3 z M 17 8 L 5.2597656 19.740234 C 5.2597656 19.740234 6.1775313 19.658 6.5195312 20 C 6.8615312 20.342 6.58 22.58 7 23 C 7.42 23.42 9.6438906 23.124359 9.9628906 23.443359 C 10.281891 23.762359 10.259766 24.740234 10.259766 24.740234 L 22 13 L 17 8 z M 4 23 L 3.0566406 25.671875 A 1 1 0 0 0 3 26 A 1 1 0 0 0 4 27 A 1 1 0 0 0 4.328125 26.943359 A 1 1 0 0 0 4.3378906 26.939453 L 4.3632812 26.931641 A 1 1 0 0 0 4.3691406 26.927734 L 7 26 L 5.5 24.5 L 4 23 z"></path>
                        </svg></a>
                        <a class="btn btn-danger" role="button" href="{% url 'eliminar_producto' p.id %}"><svg xmlns="http://www.w3.org/2000/svg" x="0px" y="0px" width="20" height="20" viewBox="0 0 30 30">
                            <path d="M 14.984375 2.4863281 A 1.0001 1.0001 0 0 0 14 3.5 L 14 4 L 8.5 4 A 1.0001 1.0001 0 0 0 7.4863281 5 L 6 5 A 1.0001 1.0001 0 1 0 6 7 L 24 7 A 1.0001 1.0001 0 1 0 24 5 L 22.513672 5 A 1.0001 1.0001 0 0 0 21.5 4 L 16 4 L 16 3.5 A 1.0001 1.0001 0 0 0 14.984375 2.4863281 z M 6 9 L 7.7929688 24.234375 C 7.9109687 25.241375 8.7633438 26 9.7773438 26 L 20.222656 26 C 21.236656 26 22.088031 25.241375 22.207031 24.234375 L 24 9 L 6 9 z"></path>
                        </svg></a>
                        
                    </td>
                </tr>
{% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</main>    



{% endblock contenido %}

templates/signup.html
{% extends 'base.html' %}
{% load static %}


{% block contenido %}

<main class="container">
    <div class="row">
        <div class="col-12">
        </div>
        <div class="col-md-4 offset-md-4">            
            <form action="{% url 'signup' %}" method="POST" class="card mt-5 mb-5">
                {% csrf_token %}
                {{error}}
                <h1 class="titulo">Crear cuenta</h1>
                <div class="card-body">
                  <div class="form-group mt-3">
                    <label for="username">Nombre de usuario:</label>
                    <input class="form-control" name="username" autocomplete="username" id="username" type="text" placeholder="Ingrese el usuario" required>
                  </div>
  
                  <div class="form-group mt-3">
                    <label for="id_password1">Contraseña:</label>
                    <input class="form-control" name="password1" id="id_password1" type="password" placeholder="Ingrese la contraseña" required>
                  </div>
  
                  <div class="form-group mt-3">
                    <label for="id_password2">Confirmar contraseña:</label>
                    <input class="form-control" name="password2" id="id_password2" type="password" placeholder="Repita la contraseña" required>
                  </div>
                  <div class="">
                        <button class="btn btn-dark mt-3" style="width: 100%;">Crear Cuenta</button>
                  </div>
                </div>
              </form>
        </div>
    </div>

</main>


{% endblock contenido %}
    